# Generated by Django 6.0.4 on 2026-06-01 04:07

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.users.models.validate_date_not_in_future], verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Introduce un correo electrónico válido.')], verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='names',
            field=models.CharField(max_length=150, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surnames',
            field=models.CharField(max_length=150, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{7,15}$')], verbose_name='teléfono'),
        ),
    ]
